ARG DEBIAN_DIST=bookworm
FROM debian:$DEBIAN_DIST

ARG DEBIAN_DIST
ARG workmux_VERSION
ARG BUILD_VERSION
ARG FULL_VERSION
ARG ARCH
ARG WM_RELEASE

RUN mkdir -p /output/usr/bin
RUN mkdir -p /output/usr/share/doc/workmux
RUN mkdir -p /output/usr/share/bash-completion/completions
RUN mkdir -p /output/usr/share/fish/vendor_completions.d
RUN mkdir -p /output/usr/share/zsh/vendor-completions
RUN mkdir -p /output/DEBIAN

COPY ${WM_RELEASE}/workmux /output/usr/bin/workmux
# Completions are generated by build_*.sh from the amd64 binary; they are
# architecture independent.
COPY completions/workmux.bash /output/usr/share/bash-completion/completions/workmux
COPY completions/workmux.fish /output/usr/share/fish/vendor_completions.d/workmux.fish
COPY completions/_workmux /output/usr/share/zsh/vendor-completions/_workmux
RUN chmod 755 /output/usr/bin/workmux
# The files copied in from the build host inherit its umask; normalise them
# so the package never ships group-writable files.
RUN chmod 644 /output/usr/share/bash-completion/completions/workmux \
      /output/usr/share/fish/vendor_completions.d/workmux.fish \
      /output/usr/share/zsh/vendor-completions/_workmux
COPY output/DEBIAN/control /output/DEBIAN/
COPY output/DEBIAN/postinst /output/DEBIAN/postinst
RUN chmod 755 /output/DEBIAN/postinst
COPY output/copyright /output/usr/share/doc/workmux/
COPY output/changelog.Debian /output/usr/share/doc/workmux/
COPY output/README.md /output/usr/share/doc/workmux/
RUN chmod 644 /output/usr/share/doc/workmux/*

RUN sed -i "s/DIST/$DEBIAN_DIST/" /output/usr/share/doc/workmux/changelog.Debian
RUN sed -i "s/FULL_VERSION/$FULL_VERSION/" /output/usr/share/doc/workmux/changelog.Debian
RUN sed -i "s/DIST/$DEBIAN_DIST/" /output/DEBIAN/control
RUN sed -i "s/workmux_VERSION/$workmux_VERSION/" /output/DEBIAN/control
RUN sed -i "s/BUILD_VERSION/$BUILD_VERSION/" /output/DEBIAN/control
RUN sed -i "s/SUPPORTED_ARCHITECTURES/$ARCH/" /output/DEBIAN/control

RUN dpkg-deb --build /output /workmux_${FULL_VERSION}.deb
